server:
  port: 8080

spring:
  application:
    name: operis-gateway
  config:
    import: optional:configserver:/
  cloud:
    config:
      discovery:
        service-id: operis-config-server
        enabled: true
