server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: operis-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://operis-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AddRequestHeader=User-Request, Gateway
        - id: task-service
          uri: lb://operis-task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - AddRequestHeader=Order-Request, Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


