server:
  port: 8080

spring:
  application:
    name: operis-gateway
  config:
    import: optional:configserver:/
  cloud:
    config:
      discovery:
        service-id: operis-config-server
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false

tracing:
  url: http://localhost:4317