server:
  port: 8081

spring:
  application:
    name: operis-user-account-service
  config:
    import: optional:configserver:/
  cloud:
    config:
      discovery:
        service-id: operis-config-server
        enabled: true

