server:
  port: 8082

spring:
  application:
    name: operis-project-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.cloud.loadbalancer: DEBUG

springdoc:
  api-docs:
    path: /project-service/v3/api-docs

  swagger-ui:
    config-url: /project-service/v3/api-docs/swagger-config
    path: /project-service/swagger-ui.html
    url: /project-service/v3/api-docs
