server:
  port: 8084

spring:
  application:
    name: operis-subscription-service
  config:
    import: optional:configserver:/
  cloud:
    config:
      discovery:
        service-id: operis-config-server
        enabled: true

