version: '3.8'

services:
  eureka:
    image: ibouakl/operis-discovery:1.0-SNAPSHOT
    container_name: operis-discovery
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  config-server:
    image: ibouakl/operis-config:1.0-SNAPSHOT
    container_name: operis-config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
    networks:
      - mynetwork
    depends_on:
      - eureka

  user-service:
    image: ibouakl/operis-user-service:1.0-SNAPSHOT
    container_name: operis-user-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://userdb:3306/operis-user
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
    depends_on:
      - eureka
      - userdb
      - config-server

  user-profile-service:
    image: ibouakl/operis-user-profile-service:1.0-SNAPSHOT
    container_name: operis-user-profile-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://userprofiledb:3306/operis-user-profile
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
    depends_on:
      - eureka
      - userprofiledb
      - config-server
    ports:
      - "8083:8083" # Optional, for local access

  task-service:
    image: ibouakl/operis-task-service:1.0-SNAPSHOT
    container_name: operis-task-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://taskdb:3306/operis-task
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
    depends_on:
      - eureka
      - taskdb
      - config-server

  gateway:
    image: ibouakl/operis-gateway:1.0-SNAPSHOT
    container_name: operis-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
    networks:
      - mynetwork
    depends_on:
      - eureka
      - user-service
      - task-service
      - config-server

  userdb:
    image: mysql:latest
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis-user
    ports:
      - "3307:3306"  # Optional, for local access
    networks:
      - mynetwork
    volumes:
      - userdb-data:/var/lib/mysql

  taskdb:
    image: mysql:latest
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis-task
    ports:
      - "3308:3306"  # Optional, for local access
    networks:
      - mynetwork
    volumes:
      - taskdb-data:/var/lib/mysql

  userprofiledb:
    image: mysql:latest
    container_name: userprofiledb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis-user-profile
    ports:
      - "3309:3306"  # Optional, for local access
    networks:
      - mynetwork
    volumes:
      - userprofiledb-data:/var/lib/mysql

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OpenTelemetry collector grpc
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  userdb-data:
  taskdb-data:
  userprofiledb-data:
