version: '3.8'

services:
  eureka:
    image: ibouakl/operis-discovery:1.0-SNAPSHOT
    container_name: operis-discovery
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  config-server:
    image: ibouakl/operis-config:1.0-SNAPSHOT
    container_name: operis-config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
    networks:
      - mynetwork
    depends_on:
      - eureka

  user-account-service:
    image: ibouakl/operis-user-account-service:1.0-SNAPSHOT
    container_name: operis-user-account-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://useraccountdb:3306/operis-user-account
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
    depends_on:
      - eureka
      - useraccountdb
      - config-server

  user-profile-service:
    image: ibouakl/operis-user-profile-service:1.0-SNAPSHOT
    container_name: operis-user-profile-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://userprofiledb:3306/operis-user-profile
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
    depends_on:
      - eureka
      - userprofiledb
      - config-server
    ports:
      - "8083:8083" # Optional, for local access

  project-service:
    image: ibouakl/operis-project-service:1.0-SNAPSHOT
    container_name: operis-project-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://projectdb:3306/operis-project
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
    depends_on:
      - eureka
      - projectdb
      - config-server

  subscription-service:
    image: ibouakl/operis-subscription-service:1.0-SNAPSHOT
    container_name: operis-subscription-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://susbcriptiondb:3306/operis-subscription
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
    depends_on:
      - eureka
      - susbcriptiondb
      - config-server
    ports:
      - "8084:8084" # Optional, for local access

  gateway:
    image: ibouakl/operis-gateway:1.0-SNAPSHOT
    container_name: operis-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://operis-discovery:8761/eureka/
    networks:
      - mynetwork
    depends_on:
      - eureka
      - user-account-service
      - project-service
      - config-server

  useraccountdb:
    image: mysql:latest
    container_name: useraccountdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis-user-account
    ports:
      - "3307:3306"  # Optional, for local access
    networks:
      - mynetwork
    volumes:
      - useraccountdb-data:/var/lib/mysql

  projectdb:
    image: mysql:latest
    container_name: projectdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis-project
    ports:
      - "3308:3306"  # Optional, for local access
    networks:
      - mynetwork
    volumes:
      - projectdb-data:/var/lib/mysql

  susbcriptiondb:
    image: mysql:latest
    container_name: susbcriptiondb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis-subscription
    ports:
      - "3310:3306"  # Optional, for local access
    networks:
      - mynetwork
    volumes:
      - susbcriptiondb-data:/var/lib/mysql

  userprofiledb:
    image: mysql:latest
    container_name: userprofiledb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis-user-profile
    ports:
      - "3309:3306"  # Optional, for local access
    networks:
      - mynetwork
    volumes:
      - userprofiledb-data:/var/lib/mysql

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OpenTelemetry collector grpc
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  useraccountdb-data:
  projectdb-data:
  userprofiledb-data:
  susbcriptiondb-data:
